// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoUbbwk7SGmbheqbvhhUq97u9gH_5cQcI',
    appId: '1:239280911339:web:4288c01f2a9d39770f5fae',
    messagingSenderId: '239280911339',
    projectId: 'first-app-d02a7',
    authDomain: 'first-app-d02a7.firebaseapp.com',
    databaseURL: 'https://first-app-d02a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-d02a7.firebasestorage.app',
    measurementId: 'G-ZK4JL7KSYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbxCUelH_K6qzfjWz6G234ECQlHj2voJo',
    appId: '1:239280911339:android:21d9b73c3acbd6960f5fae',
    messagingSenderId: '239280911339',
    projectId: 'first-app-d02a7',
    databaseURL: 'https://first-app-d02a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-d02a7.firebasestorage.app',
  );
}
